# Generated by Django 5.0.1 on 2024-02-13 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="search_user",
            options={"ordering": ["-date_creation"]},
        ),
        migrations.AddField(
            model_name="search_user",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
