# Generated by Django 5.0.1 on 2024-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0002_alter_search_user_options_search_user_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search_user",
            name="date_creation",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
