# Generated by Django 5.0.1 on 2024-02-14 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0004_data_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="slug",
        ),
    ]
