# Generated by Django 5.0.1 on 2024-02-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0005_remove_data_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
