# Generated by Django 5.0.1 on 2024-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0007_alter_search_user_auteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="hopitaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=400)),
                ("Biometrie", models.CharField(max_length=400)),
                ("Quartier", models.CharField(max_length=400)),
                ("Localisation", models.CharField(max_length=400)),
                ("Telephone", models.CharField(max_length=400)),
                ("categori", models.CharField(max_length=400)),
            ],
        ),
    ]
